### ISSUE TITLE
Test frontend

### ISSUE THREAD

**Issue by LaloVene** [LaloVene/MLH-PE-Project#137]
We can use react-testing library. That uses jest

Repo I did with testing (for reference):
[https://github.com/LaloVene/react-certification-2021/tree/feat/state-management](https://github.com/LaloVene/react-certification-2021/tree/feat/state-management)

You can run test with:
- npx jest
- npx jest --coverage
- npx --jest watch ./src/<filepath> (Auto reloads for file)

**Comment by angelaw7** [comment]
Test frontend components:
- [ ] Category Button
- [ ] Category Card
- [ ] Editable Project Card
- [ ] Project Card
- [ ] Header
- [ ] Not Found
- [ ] Page Container
- [ ] Profile Header
- [ ] Project Tags
- [ ] Search Bar
